spring:
  h2:
    console:
      enabled: true
      path: /h2emb
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true

logging:
  level:
    org:
      hibernate:
        type: trace
